### ISSUE TITLE
punctuation in comments dont parse

### ISSUE THREAD

**Issue by hklarner** [colomoto/bioLQM#10]
if I use punctutions like `? " .` in comments the parser currently throws an `token recognition error at` error. this booleannet file

```
# this is a comment?
EGF *= 1
ERBB1 *= EGF
```
does not parse

**Comment by aurelien-naldi** [comment]
this should now be fixed in the bnet parser. If it works for you I'll use the same trick for the other antlr-based ones

**Comment by hklarner** [comment]
works
