### ISSUE TITLE
Export: option to use node names instead of IDs

### ISSUE THREAD

**Issue by pauleve** [colomoto/bioLQM#17]
When converting a sbml-qual model to bnet, pint, etc., bioLQM uses the nodeID as variable name. It would be useful to be able to choose to use the name instead.

Here is a test model:
[model.sbml.txt](https://github.com/colomoto/bioLQM/files/3256129/model.sbml.txt)

The conversion will output nodes with names of the form S_X, whereas pretty name are also loaded.

**Comment by aurelien-naldi** [comment]
It would be useful indeed, we have a similar (but less complicated) problem in GINsim where we store both name and ID but only use the ID for display purpose.

The main problem would be that names can be anything: they contain spaces and plenty of characters turning them into invalid identifiers, or messing up with function parsers. They can also be duplicated in a model. In the end, we can only do this kind of transformation for the models where the names behave well.

When loading a SBML qual model, bioLQM retains both the ID and the name, I would make sense to add a new model modifier to try to make new IDs based on names. It would be cleaner than an import or export option and allow to apply this kind of "cleanup" to any model.

**Comment by pauleve** [comment]
Indeed, a model modifier is a nice way to address this issue! Something like "sanitize"?

**Comment by pauleve** [comment]
Works pretty well, and fixes the conversion from CellCollective:
https://nbviewer.jupyter.org/github/colomoto/colomoto-docker/blob/master/tutorials/CellCollective/CellCollective%20-%20Knowledge%20Base.ipynb
