### ISSUE TITLE
perturbation on booleanized model leads to infinite recursion

### ISSUE THREAD

**Issue by pauleve** [colomoto/bioLQM#20]
When applying "booleanize" modification and then "perturbation" on the resulting model, an infinite recursion occurs leading to stack overlowing.
Here is a notebook showing the behaviour:
https://nbviewer.jupyter.org/gist/pauleve/b413da4ffeeddddb7563799b0a8c02c9

**Comment by aurelien-naldi** [comment]
Indeed, there is something very wrong with the part which tries to keep track of the Boolean mapping when cloning a model. It is easy to fix it by loosing this information. It should be possible to inject it back into the cloned model afterwards.

**Comment by aurelien-naldi** [comment]
Fixed in bioLQM, it will be in the next nightly build of GINsim
